### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by tgrantjr** [ShaunPrice/FSEQLib#9]
I am trying to compile for a wemos d1 mini and getting the error of SDFSFormatter.h: No such file or directory.  I cant seem to get past it no matter what libraries i download.  Thanks

**Comment by ShaunPrice** [comment]
I just tried it using [PlatformIO](https://platformio.org/) and had no issues. It's common to have multiple versions of the SD library in the path which causes issues. I use [PlatformIO](https://platformio.org/) because isolates the environments which eliminates these issues.

Try your project on [PlatformIO](https://platformio.org/). This library and it's dependencies are all on [PlatformIO](https://platformio.org/). I've attached the INI file [platformio.ini.txt](https://github.com/ShaunPrice/FSEQLib/files/7793140/platformio.ini.txt) for the project below (rename to platformio.ini) or create a new project for the ESP you have and add the following two libraries to it.

	shaunprice/FSEQLib@^2.0.0
	fastled/FastLED@^3.4.0

**Comment by tgrantjr** [comment]
Ill be honest.  I have no idea what im doing and cant get anything to work or load.  Im trying and it just wont work for me.  I may just have to get a pi zero and load fpp on it so i also have the audio

**Comment by ShaunPrice** [comment]
Let me help you another way. I have attached the compiled binary file for the Wemos D1 Mini in the zip below. Use [NodeMCU-Flasher](https://github.com/nodemcu/nodemcu-flasher) to upload the unzipped binary file to your Wemos. 

The pins are set as follows:

SD Card SPI PINS (ESP8266 - Wemos D1 R2 mini)
==============================================
SCLK = D5/GPIO 14
MISO = D6/GPIO 12
MOSI = D7/GPIO 13
SS   = D8/GPIO 15
CD/CARD_DETECT = D3/ GPIO 0

The data pin for the lights is D2/GPIO 4.

It's set for 150 pixels but hat doesn't mean you need 150 pixels. Just use what pixels you want but make the show in Xlights have 150 pixels and don't use some of them.

[firmware.zip](https://github.com/ShaunPrice/FSEQLib/files/7797389/firmware.zip)
.

**Comment by tgrantjr** [comment]
Thank you so much. Is there a possibility of getting one for an esp32?  I also ordered a few of those. Thank you

**Comment by ShaunPrice** [comment]
Sure. Did you order any particular ESP32?

**Comment by tgrantjr** [comment]
Teyleten Robot ESP32S ESP32 ESP-WROOM-32 Development Board 2.4GHz Dual-Core WiFi +Bluetooth 2 Function Microcontroller for Arduino (ESP32 30P, 3PCS)

**Comment by ShaunPrice** [comment]
This should work. It looks like it's a generic ESP32 Dev board. 

For the ESP32 the pins change to:

SCLK = 18
MISO = 19
MOSI = 23
SS = 5
CARD_DETECT_PIN  = 17	
DATA_PIN_1 = 13 // Data pin for the lights

[firmware.zip](https://github.com/ShaunPrice/FSEQLib/files/7804506/firmware.zip)

**Comment by ShaunPrice** [comment]
Are you OK for me to close the issue out?

**Comment by tgrantjr** [comment]
Works for me. Thank you so much for the help.
